### ISSUE TITLE
Icon state is unnoticeable

### ISSUE THREAD

**Issue by erikw** [twolfson/livereload-extensions#1]
Firs toff, thanks a lot for forking off this!

As mentioned in https://github.com/livereload/livereload-extensions/issues/47, the icon when activated only get a little tiny dot filled in the middle, which is really hard to see.

Inactive:
![screen shot 2017-11-17 at 10 54 46](https://user-images.githubusercontent.com/175286/32941331-c000b428-cb85-11e7-8ecf-c320c23ecb74.png)

Active:
![screen shot 2017-11-17 at 10 46 35](https://user-images.githubusercontent.com/175286/32941018-b09121a4-cb84-11e7-81c7-bc13510b6a22.png)

Desired fix; make the icon stand out much more, so one know when the plugin is active or not.

Thanks,

**Comment by twolfson** [comment]
I have mixed feelings about this since any aesthetic work done on this fork is likely to be the upstream maintainer preferences. Do we think this is a worthwhile time investment?

**Comment by erikw** [comment]
I just tried it on Chrome, and it looks even worse, as I can not distinguish enabled from disabled at all :O.

<img width="30" alt="screen shot 2017-11-17 at 20 29 49" src="https://user-images.githubusercontent.com/175286/32965213-2b8e0db2-cbd6-11e7-89b2-e3aa52bfff5d.png">
<img width="26" alt="screen shot 2017-11-17 at 20 29 54" src="https://user-images.githubusercontent.com/175286/32965214-2babd2ca-cbd6-11e7-8a2e-f5b3d154f107.png">

I guess this should be fixed "upstream" in the Chrome extension.

**Comment by twolfson** [comment]
Cool, going to close this issue for now then. Feel free to re-open this issue if/when we want to move forward with it

**Comment by REJack** [comment]
colored icons would be great 😃

**Comment by twolfson** [comment]
If someone would like to pursue this as a PR, let me know and I'll re-open the issue

**Comment by REJack** [comment]
I've create a PR #3, check this out guys 😄

**Comment by twolfson** [comment]
Reopening this so #3 can close it

**Comment by twolfson** [comment]
This has been resolved by @REJack in #3. It's been submitted to addons.mozilla.org and should be release shortly

**Comment by erikw** [comment]
Whoop thanks!
