### ISSUE TITLE
Please update the info an AMO

### ISSUE THREAD

**Issue by jnachtigall** [twolfson/livereload-extensions#7]
I just installed it. Various things could be better:

1. Trying to find it via https://addons.mozilla.org/en-US/firefox/search/?q=live%20reload&platform=WINNT&appver=61.0a1 => Please update the two old icons:

![image](https://user-images.githubusercontent.com/3307404/39118365-8898c216-46e9-11e8-94b5-7e4477752c31.png)

and

![image](https://user-images.githubusercontent.com/3307404/39118198-1bfedffa-46e9-11e8-8696-e16b07473dbf.png)

to this:

![image](https://user-images.githubusercontent.com/3307404/39118234-353b53ea-46e9-11e8-82e4-c88b396c95c4.png)

Also, there's really no real description at https://addons.mozilla.org/en-US/firefox/addon/livereload-web-extension/?src=search 

(especially since the original plugin should be considered abandanded)

**Comment by twolfson** [comment]
I still am considering this a temporary fix (I don't have time to prioritize this with full maintenance) and so I don't want people taking it too seriously. Going to leave things as they are =/
